[package]
name = "trading-bot"
version = "0.1.0"
authors = ["shardamaka <mariusalexandrutache@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }